# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CICD

on:
  push:
    branches: ["noah"]

jobs:
  push_to_registry:
    name: Run Tests and Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: noah4575/git_lab2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: noah4575/git_lab2:noah
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run tests
        run: |
          docker run --name test_container -d noah4575/git_lab2:latest
          docker exec test_container python -m unittest discover

      - name: Push to Docker Hub
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: noah4575/git_lab2:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Debug Info
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "GITHUB_TOKEN: $DOCKER_TOKEN"
          # Add more debug information as needed
