# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CICD

on:
  push:
    branches: [ "noah" ]

jobs:
  push_to_registry:
    name: Run Tests and Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a 
      with:
        username: ${{ secrets.DOCKEr_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: noah4575/git_lab2

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: noah4575/ci-cd-with-github-actions:noah
        labels: ${{ steps.meta.outputs.labels }}

    - name: Run tests
      run: |
        docker run --name test_container -d noah4575/git_lab2:noah
        docker exec test_container python -m unittest discover

    - name: Push to Docker Hub
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: noah4575/git_lab2:noah
        labels: ${{ steps.meta.outputs.labels }}

      - name: Debug Info
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "GITHUB_TOKEN: $DOCKER_TOKEN"
          # Add more debug information as needed
